import mongoose from "mongoose";

const recruitingagencySchema=new mongoose.Schema({
    full_name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
      type:String,
      required:true
    },
    mobileno:{
        type:String,
        required:true
    },
    agency_type:{
        type:String,
        required:true
    },
    expertise_area:{
        type:String,
    },
    year_of_experience:{
        type:String,
    },
    company_name:{
        type:String,
    },
    company_description:{
       type:String
    },
    company_age:{
      type:String
    },
    country_preference_one:{
      type:String
    },
    country_preference_two:{
      type:String
    },
    certificate_of_incorporation:{
      filename:String,
      filepath:String,
      filetype:String
    },
    experience_usa_sourcing:{
      type:Boolean,
      default:false
    },
    company_size:{
        type:String,
    },
    designation:{
        type:String,
    },
    linkedin_url:{
        type:String,
        required:true
    },
    firm_type:{
        type:[String]
    },
    country:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    domains:{
        type:[String]
    },
    email_verified:{
        type:Boolean,
        default:false
    },
    kyc_verified:{
        type:Boolean,
        default:false
    },
    kyc_details:{
        entity_type:String,
        pancard_number:String,
        gst_no:String
    },
    kyc_documents:{
      filename:String,
      filepath:String,
      filetype:String
    },
    account_status:{
        type:Object,
        default:{
            status:"Active",
            remark:"",
            admin_id:""
        }
    },
    admin_verified:{
        type:Boolean,
        default:false
    },
    alloted_account_manager:{
        type:String,
    },
    account_manager_verified:{
        type:Boolean,
        default:false
    },
    
    

},{timestamps:true})

export default mongoose.model("Recruiting",recruitingagencySchema)