// Mapping of section name with candidate status
export const cstatus = new Map([
    ['Pending','Under Review'],
    ['newresume',"New Resume"],
    ['rs-cc','Resume Select - Client Recruiter'],
    ['rs-hm','Resume Select - Hiring Manager'],
    ['test-process','Test in Process'],
    ['interview-process','Interview in Process'],
    ['no-show','No Show'],
    ['candidate-not-ins','Candidate Not Interested'],
    ['candidate-not-reach','Candidate Not Reachable'],
    ['rr-cc','Resume Reject - Client Recruiter'],
    ['rr-hm','Resume Reject - Hiring Manager'],
    ['r-test','Rejected in Test'],
    ['rjt-tech-itw','Rejected in Tech Interview'],
    ['rjt-hr-itw','Rejected in HR Interview'],
    ['s-f-itw','Selected in Final Interview'],
    ['s-not-offer',"Selected - Won't be Offered"],
    ['o-released','Offer Released'],
    ['o-accepted','Offer Accepted'],
    ['o-rejected','Offer Rejected'],
    ['c-not-joine','Candidate Not Joining'],
    ['c-joine','Candidate Joined'],
    ['quit-after-joine','Quit After Joining'],
    ['on-hold','On Hold'],
    ['no-action','No Further Action'],
    ['use-later','Use Later'],
  ]);