// Mapping of section name with candidate status
export const cstatus = new Map([
    ['Pending','Under Review'],
    ['resumesubmit',"Resume Submitted"],
    ['sip','Screening in Progress'],
    ['cvshortclient','CV Shortlisted – Client Recruiter'],
    ['cvshorthr','CV Shortlisted – Hiring Manager'],
    ['interview-schedule','Interview Scheduled'],
    ['no-show','No Show'],
    ['candidate-not-ins','Candidate Not Interested'],
    ['candidate-not-reach','Candidate Not Reachable'],
    ['cv-reject-client','CV Rejected – Client Recruiter'],
    ['cv-reject-hr','CV Rejected – Hiring Manager'],
    ['r-techround','Rejected – Technical Round'],
    ['r-hrround','Rejected – HR Round'],
    ['short-next-round','Shortlisted for Next Round'],
    ['s-finale-interview',"Selected in Final Interview"],
    ['s-not-offer','Selected – Not Offered'],
    ['o-hold','On Hold'],
    ['o-extended','Offer Extended'],
    ['o-accepted','Offer Accepted'],
    ['o-declined','Offer Declined'],
    ['not-join','Did Not Join'],
    ['success-joined','Successfully Joined'],
    ['payout-eligible','Payout Eligible'],
    ['early-registration','Early Resignation'],
    ['cv-rejected','CV Rejected - In Process'],
    ['invoice-raised','Invoice Raised'],
    ['payment-received', 'Payment Received'],
    ['credit-note', 'Credit Note']
  ]);

export const statusStyle = new Map([
    ['Pending', 'border-yellow-500 bg-yellow-100'],
    ['resumesubmit', 'border-green-500 bg-green-100'],
    ['sip', 'border-yellow-500 bg-yellow-100'],
    ['cvshortclient', 'border-orange-500 bg-orange-100'],
    ['interview-schedule', 'border-orange-500 bg-orange-100'],
    ['no-show', 'border-red-500 bg-red-100'],
    ['candidate-not-ins', 'border-red-500 bg-red-100'],
    ['candidate-not-reach', 'border-red-500 bg-red-100'],
    ['cv-reject-client', 'border-red-500 bg-red-100'],
    ['cv-reject-hr', 'border-red-500 bg-red-100'],
    ['r-techround','border-red-500 bg-red-100'],
    ['r-hrround', 'border-red-500 bg-red-100'],
    ['short-next-round', 'border-orange-500 bg-orange-100'],
    ['s-finale-interview', 'border-green-500 bg-green-100'],
    ['s-not-offer', 'border-red-500 bg-red-100'],
    ['o-hold', 'border-red-500 bg-red-100'],
    ['o-extended', 'border-red-500 bg-red-100'],
    ['o-accepted', 'border-green-500 bg-green-100'],
    ['o-declined', 'border-red-500 bg-red-100'],
    ['not-join', 'border-red-500 bg-red-100'],
    ['success-joined','border-green-500 bg-green-100'],
    ['payout-eligible', 'border-green-500 bg-green-100'],
    ['early-registration', 'border-red-500 bg-red-100'],
    ['cv-rejected','border-red-500 bg-red-100'],
    ['invoice-raised', 'border-orange-500 bg-orange-100'],
    ['payment-received','border-green-500 bg-green-100'],
    ['credit-note', 'border-red-500 bg-red-100']
])

