// Mapping of section name with candidate status
export const cstatus = new Map([
  ['Pending','Under Review'],
  ['resumesubmit',"Resume Submitted"],
  ['sip','Screening in Progress'],
  ['cvshortclient','CV Shortlisted – Client Recruiter'],
  ['cvshorthr','CV Shortlisted – Hiring Manager'],
  ['interview-schedule','Interview Scheduled'],
  ['no-show','No Show'],
  ['candidate-not-ins','Candidate Not Interested'],
  ['candidate-not-reach','Candidate Not Reachable'],
  ['cv-reject-client','CV Rejected – Client Recruiter'],
  ['cv-reject-hr','CV Rejected – Hiring Manager'],
  ['r-techround','Rejected – Technical Round'],
  ['r-hrround','Rejected – HR Round'],
  ['short-next-round','Shortlisted for Next Round'],
  ['s-finale-interview',"Selected in Final Interview"],
  ['s-not-offer','Selected – Not Offered'],
  ['o-hold','On Hold'],
  ['o-extended','Offer Extended'],
  ['o-accepted','Offer Accepted'],
  ['o-declined','Offer Declined'],
  ['not-join','Did Not Join'],
  ['success-joined','Successfully Joined'],
  ['payout-eligible','Payout Eligible'],
  ['early-registration','Early Resignation'],
  ['cv-rejected','CV Rejected - In Process'],
  ['invoice-raised','Invoice Raised'],
  ['payment-received', 'Payment Received'],
  ['creditnote','Credit Note']
  ]);